
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqqyfoznvstdbmmuvhwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcXlmb3pudnN0ZGJtbXV2aHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODAxNDksImV4cCI6MjA1OTc1NjE0OX0.0-RIjJQ8uSMjYxQDsYaWeVfwp6ViQFkBb5wUz7VOSpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
